# Use uma imagem oficial do Python como imagem pai
FROM python:3.8-slim

# Defina o diretório de trabalho para /app
WORKDIR /app

# Copie o conteúdo do diretório atual para o contêiner em /app
COPY . /app

# Instale os pacotes necessários especificados em requirements.txt
RUN pip install -r requirements.txt

# Defina o comando CMD para executar os testes
CMD ["pytest"]
